certbot_image: certbot/certbot
certbot_hostname: cert01
certbot_data_dir: /usr/share/certbot
certbot_email: info@mint-system.ch

nginx_image: nginx:1.15-alpine
nginx_hostname: proxy01
nginx_data_dir: /usr/share/nginx
nginx_proxies:
  - src_hostname: wiki.mint-system.ch
    src_port: 443
    dest_hostname: book01
    dest_port: 80
  - src_hostname: odoo.mint-system.ch
    src_port: 443
    dest_hostname: odoo01
    dest_port: 8069
  - src_hostname: cloud.mint-system.ch
    src_port: 443
    dest_hostname: nextcloud01
    dest_port: 80

modsecurity_image: owasp/modsecurity:3-nginx
modsecurity_data_dir: /usr/share/modsecurity
modsecurity_crs_url: "https://github.com/SpiderLabs/owasp-modsecurity-crs/archive/v3.2.0.tar.gz"
modsecurity_engine_mode: DetectionOnly
modsecurity_http_allowed_methods: "GET HEAD POST OPTIONS PUT PATCH DELETE CHECKOUT COPY DELETE LOCK MERGE MKACTIVITY MKCOL MOVE PROPFIND PROPPATCH PUT UNLOCK"
# modsecurity_remove_rules:
