all:
  hosts:
  children:
    local:
      hosts: localhost
    zeus:
      hosts: zeus.mint-system.com
      vars:
        ansible_python_interpreter: /usr/bin/python3
    hades:
      hosts: hades.mint-system.com
      vars:
        ansible_python_interpreter: /usr/bin/python3