- hosts: all
  become: true
  roles:
  - role: docker
    tags: docker
  - role: docker-network
    tags: docker-network
  - role: elasticsearch
    tags: elasticsearch
  - role: kibana
    tags: kibana