certbot_hostname: cert02
certbot_data_dir: /usr/share/certbot02
certbot_email: info@mint-system.ch

nginx_hostname: proxy02
nginx_data_dir: /usr/share/nginx02
nginx_proxies:
  - src_hostname: hades.mint-system.com
    src_port: 443
    dest_hostname: odoo02
    dest_port: 8069
  - src_hostname: odoo.mint-system.ch
    src_port: 443
    dest_hostname: odoo02
    dest_port: 8069

modsecurity_data_dir: /usr/share/modsecurity01