certbot_image: certbot/certbot
certbot_stat_filter: "results[*] | [?stat.exists==`false`].item"

nginx_image: nginx:1.15-alpine

modsecurity_image: owasp/modsecurity:3-nginx
modsecurity_crs_url: "https://github.com/SpiderLabs/owasp-modsecurity-crs/archive/v3.2.0.tar.gz"
# Options: On, DetectionOnly
modsecurity_engine_mode: "On"
modsecurity_default_action: "phase:1,deny,log"
modsecurity_http_allowed_methods: "GET HEAD POST OPTIONS PUT PATCH DELETE CHECKOUT COPY DELETE LOCK MERGE MKACTIVITY MKCOL MOVE PROPFIND PROPPATCH PUT UNLOCK SEARCH REPORT"
modsecurity_request_allowed_content_type: "application/x-www-form-urlencoded|multipart/form-data|text/xml|application/xml|application/soap+xml|application/x-amf|application/json|application/octet-stream|application/csp-report|application/xss-auditor-report|text/plain|image/png|image/jpg"
modsecurity_exclude_rules_before_crs:
  - |
    # ModSecurity Rule Exclusion: Disable selected XSS rules for /books request uri
    SecRule REQUEST_URI "@beginsWith /books" \
        "id:1000,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveById=932100,\
        ctl:ruleRemoveById=941160,\
        ctl:ruleRemoveById=932110,\
        ctl:ruleRemoveById=932105,\
        ctl:ruleRemoveById=932130"
  - |
    # ModSecurity Rule Exclusion: Disable selected XSS rules for /web/dataset/call_kw request uri
    SecRule REQUEST_URI "@beginsWith /web/dataset/call_kw" \
        "id:1001,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveById=941100"
  - |
    # ModSecurity Rule Exclusion: Disable selected XSS rules for /images/drawio request uri
    SecRule REQUEST_URI "@beginsWith /images/drawio" \
        "id:1002,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveById=941130,\
        ctl:ruleRemoveById=941170"
  - |
    # ModSecurity Rule Exclusion: Disable selected XSS rules for /remote.php/webdavo request uri
    SecRule REQUEST_URI "@beginsWith /remote.php/webdav" \
        "id:1003,\
        phase:1,\
        pass,\
        nolog,\
        ctl:ruleRemoveById=941100"
        
modsecurity_inbound_anomaly_score_threshold: 10
