postgres_image: postgres:10-alpine
postgres_hostname: postgres03
postgres_port_exposed: 5432
postgres_data_dir: /usr/share/postgres03
postgres_volume_name: postgres_data03
postgres_user: odoo
postgres_password: "{{ vault_postgres_password }}"
postgres_db: odoo

odoo_image: odoo:13
odoo_hostname: odoo02
odoo_port: 8069
odoo_data_dir: /usr/share/odoo02
odoo_volume_name: odoo_data02
odoo_postgres_hostname: postgres03
odoo_postgres_user: odoo
odoo_postgres_password: "{{ vault_postgres_password }}"