postgres_image: postgres:10-alpine
postgres_port_exposed: 5433
postgres_user: wiki
postgres_password: "{{ vault_postgres_password }}"
postgres_db: "nextcloud"

mysql_image: mysql:5
mysql_root_password: "{{ vault_mysql_root_password }}"
mysql_database: bookstack
mysql_user: bookstack
mysql_password:  "{{ vault_mysql_password }}"

nextcloud_image: nextcloud:18-apache
nextcloud_admin_user: admint
nextcloud_admin_password: "{{ vault_nextcloud_admin_password }}"
nextcloud_postgres_user: wiki
nextcloud_postgres_password: "{{ vault_postgres_password }}"
nextcloud_postgres_db: nextcloud

bookstack_image: solidnerd/bookstack:0.27.5
bookstack_db_user: bookstack
bookstack_db_password: "{{ vault_mysql_password }}"
bookstack_db_database: bookstack
bookstack_mail_driver: smtp
bookstack_mail_hostname: mail.infomaniak.com
bookstack_mail_port: "587"
bookstack_mail_from: noreply@mint-system.ch
bookstack_mail_username: bot@mint-system.ch
bookstack_mail_password: "{{ vault_mail_password }}"
bookstack_mail_encryption: tls