all:
  hosts:
  children:
    local:
      hosts: localhost
    odoo:
      hosts:
        zeus.mint-system.com
        hades.mint-system.com
      vars:
        ansible_python_interpreter: /usr/bin/python3